module.exports = {
  ROLES: { ADMIN: "admin", TECHNICIAN: "technician", CUSTOMER: "customer" },
  BOOKING_STATUS: {
    NEW: "NEW",
    ASSIGNED: "ASSIGNED",
    ACCEPTED: "ACCEPTED",
    ON_THE_WAY: "ON_THE_WAY",
    STARTED: "STARTED",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
  },
  // Allowed forward transitions; CANCELLED reachable from any non-terminal state.
  BOOKING_TRANSITIONS: {
    NEW: ["ASSIGNED", "CANCELLED"],
    ASSIGNED: ["ACCEPTED", "CANCELLED"],
    ACCEPTED: ["ON_THE_WAY", "CANCELLED"],
    ON_THE_WAY: ["STARTED", "CANCELLED"],
    STARTED: ["COMPLETED", "CANCELLED"],
    COMPLETED: [],
    CANCELLED: [],
  },
  PAYMENT_STATUS: { PENDING: "PENDING", PAID: "PAID", PARTIAL: "PARTIAL" },
  TECH_STATUS: { AVAILABLE: "AVAILABLE", ON_JOB: "ON_JOB", OFF_DUTY: "OFF_DUTY" },
  URGENCY: { LOW: "LOW", NORMAL: "NORMAL", HIGH: "HIGH", EMERGENCY: "EMERGENCY" },
  COMMISSION_RATE: 0.18,
};
